import React from 'react';
import { render } from 'react-dom';
import Unavatar, {
  startupPalette,
  win32Palette,
  materialPalette,
  microPalette,
  applePalette,
} from '../../lib';
import './styles.css';

const people = [
  'Pam Beesly',
  'Dwight Schrute',
  'Jim Halpert',
  'Michael Scott',
  'Andy Bernard',
  'Kevin Malone',
  'Erin Hannon',
  'Toby Flenderson',
  'Angela Martin',
  'Ryan Howard',
  'Stanley Hudson',
  'Kelly Hapoor',
  'Holly Flax',
  'Meredith Palmer',
  'Creed Bratton',
  'Gabe Lewis',
  'Robert California',
  'Darryl Philbin',
  'Nellie Bertram',
  'Phyllis Vance',
  'Jan Levinson',
  'Oscar Martinez',
  'Roy Anderson',
];

class DemoApp extends React.Component {
  state = {
    palette: materialPalette,
  };

  select = palette => e => {
    e.preventDefault();
    this.setState({ palette });
  };

  render() {
    return (
      <div className="demo">
        <div className="sidebar">
          <div className="theme-switcher">
            <h2>Select theme</h2>
            <a href="#" onClick={this.select(materialPalette)}>
              Material
            </a>
            <a href="#" onClick={this.select(startupPalette)}>
              Startup
            </a>
            <a href="#" onClick={this.select(win32Palette)}>
              Win32
            </a>
            <a href="#" onClick={this.select(microPalette)}>
              Micro
            </a>
            <a href="#" onClick={this.select(applePalette)}>
              Fruit
            </a>
          </div>
          <p className="footer">
            This is a demo built with{' '}
            <a href="https://github.com/soska/unavatar">Unavatar</a>. Source
            code for this demo{' '}
            <a href="https://github.com/soska/unavatar/blob/master/src/docs/index.jsx">
              is here
            </a>.
          </p>
        </div>
        <div className="people">
          <h1>Unavatar Demo App</h1>
          <p className="instructions">
            The lovely avatars in every row are generated by the{' '}
            <code>Unavatar</code> react component. You can use the sidebar at
            the left to switch themes.
          </p>

          <table>
            <tbody>
              {people.map((person, index) => (
                <tr key={`${person}-${index}`}>
                  <td className={'avatar-cell'}>
                    <Unavatar
                      size={60}
                      name={person}
                      id={`${person}-${index}`}
                      palette={this.state.palette}
                    />
                  </td>
                  <td className={'name-cell'}>{person}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    );
  }
}

render(<DemoApp />, document.getElementById('app'));
